name: CI
on: pull_request
permissions:
  contents: read
jobs:
  ci:
    name: Run CI
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Build artifacts
        run: go build ./...
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.2
      - name: Run staticcheck
        run: staticcheck -checks all ./...
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run govulncheck
        run: govulncheck -test ./...
      - name: Run tests
        run: go test -race ./...